common:
  msg_source: 1                                         #0: not use Lidar
                                                        #1: packet message comes from online Lidar
                                                        #2: packet message comes from Pcap file
  ros_frame_id: innolidar                             #Frame id of packet message and point cloud message
  ros_send_point_cloud_topic: /innolidar_points       #Topic used to send point cloud through ROS
lidar:
  - driver:
      lidar_type: IFW192S                       #LiDAR type - IFW192S FW192SB
      point_type: 0                             #point cloud type 0(x,y,z,intensity,ring) 1(x,y,z,intensity,ring,time)
      cloud_port: 8010                          #cloud port of lidar (pc port)
      check_lidar_ip: 192.168.1.10              #check param of lidar device UDP (lidar ip)
      h_start_angle: -360                       #herizon Start angle of point cloud
      h_end_angle: 360                          #herizon End angle of point cloud 
      v_start_angle: -50                        #vertical Start angle of point cloud
      v_end_angle: 50                           #vertical End angle of point cloud
      min_distance: 0.02                        #Minimum distance of point cloud
      max_distance: 200                         #Maximum distance of point cloud
      pcap_repeat: true                         #True--repeat play pcap file
      is_device_load_calibration: false          #True--Use the lidar check param from lidar device
      calibrate_folder: /home/wenjie/Program/inno_sdk/inno_multi_driver_ws/src/inno_multi_lidar_ros/config/fw192sa #
      pcap_file: /home/wenjie/project/pcap/ifw192s/71_2.pcap #The path of pcap file
      extrinsic:
        use_status: true                        #
        roll: 0                                 #
        pitch: 0                                #
        yaw: 0                                  #
        x: 0                                    #
        y: 0                                    #
        z: 0                                    #

  - driver:
      lidar_type: IFW192S                       #LiDAR type - IFW192S FW192SB
      point_type: 0                             #point cloud type 0(x,y,z,intensity,ring) 1(x,y,z,intensity,ring,time)
      cloud_port: 8020                          #cloud port of lidar (pc port)
      check_lidar_ip: 192.168.1.20              #check param of lidar device UDP (lidar ip)
      h_start_angle: -360                       #herizon Start angle of point cloud
      h_end_angle: 360                          #herizon End angle of point cloud 
      v_start_angle: -50                        #vertical Start angle of point cloud
      v_end_angle: 50                           #vertical End angle of point cloud
      min_distance: 0.02                        #Minimum distance of point cloud
      max_distance: 200                         #Maximum distance of point cloud
      pcap_repeat: true                         #True--repeat play pcap file
      is_device_load_calibration: false          #True--Use the lidar check param from lidar device
      calibrate_folder: /home/wenjie/Program/inno_sdk/inno_multi_driver_ws/src/inno_multi_lidar_ros/config/fw192sa #
      pcap_file: /home/wenjie/project/pcap/ifw192s/71_2.pcap #The path of pcap file
      extrinsic:
        use_status: true                        #
        roll: 0                                 #
        pitch: 45                                #
        yaw: 0                                  #
        x: 0                                    #
        y: 0                                    #
        z: 0                                    #

  - driver:
      lidar_type: IFW192S                       #LiDAR type - IFW192S FW192SB
      point_type: 0                             #point cloud type 0(x,y,z,intensity,ring) 1(x,y,z,intensity,ring,time)
      cloud_port: 8030                          #cloud port of lidar (pc port)
      check_lidar_ip: 192.168.1.30              #check param of lidar device UDP (lidar ip)
      h_start_angle: -360                       #herizon Start angle of point cloud
      h_end_angle: 360                          #herizon End angle of point cloud 
      v_start_angle: -50                        #vertical Start angle of point cloud
      v_end_angle: 50                           #vertical End angle of point cloud
      min_distance: 0.02                        #Minimum distance of point cloud
      max_distance: 200                         #Maximum distance of point cloud
      pcap_repeat: true                         #True--repeat play pcap file
      is_device_load_calibration: false          #True--Use the lidar check param from lidar device
      calibrate_folder: /home/wenjie/Program/inno_sdk/inno_multi_driver_ws/src/inno_multi_lidar_ros/config/fw192sa #
      pcap_file: /home/wenjie/project/pcap/ifw192s/71_2.pcap #The path of pcap file
      extrinsic:
        use_status: true                        #
        roll: 45                                 #
        pitch: 0                                #
        yaw: 0                                  #
        x: 0                                    #
        y: 0                                    #
        z: 0                                    #

  - driver:
      lidar_type: IFW192S                       #LiDAR type - IFW192S FW192SB
      point_type: 0                             #point cloud type 0(x,y,z,intensity,ring) 1(x,y,z,intensity,ring,time)
      cloud_port: 8040                          #cloud port of lidar (pc port)
      check_lidar_ip: 192.168.1.40              #check param of lidar device UDP (lidar ip)
      h_start_angle: -360                       #herizon Start angle of point cloud
      h_end_angle: 360                          #herizon End angle of point cloud 
      v_start_angle: -50                        #vertical Start angle of point cloud
      v_end_angle: 50                           #vertical End angle of point cloud
      min_distance: 0.02                        #Minimum distance of point cloud
      max_distance: 200                         #Maximum distance of point cloud
      pcap_repeat: true                         #True--repeat play pcap file
      is_device_load_calibration: false          #True--Use the lidar check param from lidar device
      calibrate_folder: /home/wenjie/Program/inno_sdk/inno_multi_driver_ws/src/inno_multi_lidar_ros/config/fw192sa #
      pcap_file: /home/wenjie/project/pcap/ifw192s/71_2.pcap #The path of pcap file
      extrinsic:
        use_status: true                        #
        roll: 0                                 #
        pitch: 0                                #
        yaw: 45                                 #
        x: 0                                    #
        y: 0                                    #
        z: 0                                    #
        

